# Generated by Django 5.0.4 on 2024-05-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_sponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sponsors', to='app1.sponsor'),
        ),
        migrations.AlterField(
            model_name='student_sponsor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sponsors', to='app1.student'),
        ),
    ]
